/*****************************************************************************/
/********** !!! WARNING: CODE GENERATED BY TAPROOT. DO NOT EDIT !!! **********/
/*****************************************************************************/

/*
 * Copyright (c) 2020-2021 Advanced Robotics at the University of Washington <robomstr@uw.edu>
 *
 * This file is part of Taproot.
 *
 * Taproot is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Taproot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Taproot.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "spi.hpp"

#include "tap/board/board.hpp"
#include "tap/util_macros.hpp"

// Note: Avoid using interrupts due to taproot command scheduler

using namespace Board;

namespace src::communication::serial
{
bool Spi::read(SpiPort port, uint8_t* data)
{
#ifdef PLATFORM_HOSTED
    UNUSED(port);
    UNUSED(data);
    return false;
#else
    switch (port)
    {
        case SpiPort::Spi1:
            // Do nothing
            return false;
        case SpiPort::Spi2:
            SpiHal1::read(*data);
            return true;
        default:
            return false;
    }
#endif
}

bool Spi::read(SpiPort port, uint16_t* data)
{
#ifdef PLATFORM_HOSTED
    UNUSED(port);
    UNUSED(data);
    return false;
#else
    switch (port)
    {
        case SpiPort::Spi1:
            // Do nothing
            return false;
        case SpiPort::Spi2:
            // Cycle through the buffer
            SpiHal1::read(*data);
            return true;
        default:
            return false;
    }
#endif
}

bool Spi::write(SpiPort port, uint8_t data)
{
#ifdef PLATFORM_HOSTED
    UNUSED(port);
    UNUSED(data);
    return false;
#else
    switch (port)
    {
        case SpiPort::Spi1:
            return false;
        case SpiPort::Spi2:
            SpiHal::write(data);
            return true;
        default:
            return false;
    }
#endif
}

bool Spi::write(SpiPort port, uint16_t data)
{
#ifdef PLATFORM_HOSTED
    UNUSED(port);
    UNUSED(data);
    return false;
#else
    switch (port)
    {
        case SpiPort::Spi1:
            return false;
        case SpiPort::Spi2:
            SpiHal::write(data);
            return true;
        default:
            return false;
    }
#endif
}

bool Spi::isReceiveRegisterNotEmpty(SpiPort port)
{
#ifdef PLATFORM_HOSTED
    UNUSED(port);
    UNUSED(data);
    return false;
#else
    switch (port)
    {
        case SpiPort::Spi1:
            return false;
        case SpiPort::Spi2:
            return SpiHal1::isReceiveRegisterNotEmpty();
        default:
            return false;
    }
#endif
};

bool Spi::isTransmitRegisterEmpty(SpiPort port)
{
#ifdef PLATFORM_HOSTED
    UNUSED(port);
    UNUSED(data);
    return false;
#else
    switch (port)
    {
        case SpiPort::Spi1:
            return false;
        case SpiPort::Spi2:
            return SpiHal1::isTransmitRegisterEmpty();
        default:
            return false;
    }
#endif
};

}  // namespace src::communication::serial
