/*****************************************************************************/
/********** !!! WARNING: CODE GENERATED BY TAPROOT. DO NOT EDIT !!! **********/
/*****************************************************************************/

/*
 * Copyright (c) 2020-2021 Advanced Robotics at the University of Washington <robomstr@uw.edu>
 *
 * This file is part of Taproot.
 *
 * Taproot is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Taproot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Taproot.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef SPI_HPP_
#define SPI_HPP_

#include <cstdint>
#include <cstdlib>

#ifndef PLATFORM_HOSTED
#include "modm/platform.hpp"
// vvv Functions implemented on top of SpiBase/ HAL (setting dataSize, dataOrder, etc.)
#include "modm/platform/spi/spi_master_1.hpp"
// vvv Do not uncomment, useful for reference only
// #include "modm/platform/spi/spi_base.hpp"
// #include "modm/platform/spi/spi_hal_1.hpp"
#endif

#include "tap/board/board.hpp"
#include "tap/util_macros.hpp"

#include "/workspaces/robomaster/ut-robomaster/taproot/modm/src/modm/math/units.hpp"  // Jiyan- Imported this to be able to give the spi init template the pct value

namespace src::communication::serial
{
/**
 * Class that wraps modm's SPI implementation.
 *
 * Currently configured for custom SPI port (10 pin header) on DEV BOARD TYPE-C.
 */
class Spi
{
public:
    enum SpiPort
    {
        Spi1,  // ?
        Spi2,  // Custom SPI port on DEV BOARD TYPE-C, 8 PIN connector
    };

#ifdef PLATFORM_HOSTED
    ;  // Do nothing for now
#else
    using MasterSelection = modm::platform::SpiBase::MasterSelection;
    using DataMode = modm::platform::SpiBase::DataMode;
    using DataOrder = modm::platform::SpiBase::DataOrder;
    using DataSize = modm::platform::SpiBase::DataSize;
    using Prescaler = modm::platform::SpiBase::Prescaler;

#endif

    Spi() = default;
    DISALLOW_COPY_AND_ASSIGN(Spi)
    mockable ~Spi() = default;

    /**
     * Initializes a particular Spi with the pins particular to the board.
     *
     * @note follow convention in the function when adding a `SpiPort`.
     * @tparam port the particular port to initialize.
     * @tparam baudrate desired baud rate in Hz.
     * @tparam parity @see `Parity`.
     */
    template <SpiPort port, modm::baudrate_t baudrate>
    void init()
    {
#ifndef PLATFORM_HOSTED
        // ADDITIONAL CONFIGS:
        // MasterSelection masterselection = MasterSelection::Slave,
        // DataMode datamode,
        // DataOrder dataorder,
        // DataSize datasize,
        // Prescaler prescaler

        if constexpr (port == SpiPort::Spi1)
        {
            // Do nothing
        }
        if constexpr (port == SpiPort::Spi2)
        {
            // Custom SPI port on DEV BOARD TYPE-C
            // GpioB12 -- NSS, not required for whatever reason
            // GpioB13 -- CLK
            // GpioB14 -- MISO
            // GpioB15 -- MOSI

            modm::platform::SpiMaster2::connect<GpioB13::Sck, GpioB14::Miso, GpioB15::Mosi>();
            modm::platform::SpiMaster2::initialize<
                Board::SystemClock,
                baudrate,
                modm::pct(30)>();  // the tolerance argument for the template has a default value,
                                   // and the first parameter should be of type systemclock, not SPI
                                   // -- Jiyan
        }
#endif
    }

    /**
     * Read a single byte.
     *
     * @param[in] port the port to read from.
     * @param[out] data Byte read, if any.
     *
     * @return `true` if a byte was received, `false` otherwise.
     */
    mockable bool read(SpiPort port, uint8_t* data);

    /**
     * Read 2 bytes.
     *
     * @param[in] port the port to read from.
     * @param[out] data 2 Byte read, if any.
     *
     * @return `true` if a byte was received, `false` otherwise.
     */
    mockable bool read(SpiPort port, uint16_t* data);

    /**
     * Pushes a single byte on clk edge.
     *
     * @param[in] port the port to write to.
     * @return `true` if data has been successfully sent, `false` if buffer is full.
     * @note this writing is buffered.
     */
    mockable bool write(SpiPort port, uint8_t data);

    /**
     * Pushes a 2 bytes on clk edge.
     *
     * @param[in] port the port to write to.
     * @return `true` if data has been successfully sent, `false` if buffer is full.
     * @note this writing is buffered.
     */
    mockable bool write(SpiPort port, uint16_t data);

    mockable bool isReceiveRegisterNotEmpty(SpiPort port);

    mockable bool isTransmitRegisterEmpty(SpiPort port);
};

}  // namespace src::communication::serial

#endif  // SPI_HPP_
