from os.path import abspath

Import("env")
Import("args")
Import("sources")


if args["TARGET_ENV"] == "tests":
    print("etss")
    env_cpy = env.Clone()

    # Append on the global robot target build flag
    env_cpy.AppendUnique(CCFLAGS=["-D " + args["ROBOT_TYPE"]])

    rawSrcs = env_cpy.FindSourceFiles(".")

    for source in rawSrcs:
        sources.append(env_cpy.Object(source))

Return('sources')