from os.path import abspath

Import("env")
Import("args")
Import("c_flags")
Import("sources")


if args["TARGET_ENV"] == "tests":
    print("etss")
    env_cpy = env.Clone()

    # Append global build flags
    env_cpy.AppendUnique(CFLAGS=[f"-D {x}" for x in c_flags])

    rawSrcs = env_cpy.FindSourceFiles(".")

    for source in rawSrcs:
        sources.append(env_cpy.Object(source))

Return('sources')