from os.path import abspath

Import("env")
Import("args")
Import("c_flags")
Import("sources")


# Don't compile this stuff when testing
IGNORED_FILES_WHILE_TESTING = ["main.cpp"]

ignored_files = []
ignored_dirs = []

if args["TARGET_ENV"] == "tests":
    ignored_files.extend(IGNORED_FILES_WHILE_TESTING)

env_cpy = env.Clone()

# Append global build flags
env_cpy.AppendUnique(CCFLAGS=[f"-D {x}" for x in c_flags])

ignored_files.append("main_src_not_compiled.cpp")
rawSrcs = env_cpy.FindSourceFiles(".", ignorePaths=ignored_dirs, ignoreFiles=ignored_files)

for source in rawSrcs:
    sources.append(env_cpy.Object(source))

Return('sources')