name: Test building for each robot
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Podman
      uses: gacts/install-podman@v1.1.0
    - name: Build the container
      run: podman build --tag container .
    - name: Run the container
      run: podman run -dt --rm --userns keep-id:uid=1000,gid=1000 -v .:/code -w /code/ut-robomaster container
    - name: Build Standard
      run: podman exec -l scons build robot=standard
    - name: Build Hero
      run: podman exec -l scons build robot=hero
    - name: Build Sentry
      run: podman exec -l scons build robot=sentry
      
