name: Push Container
on:
  push:
    branches: ["develop"]
    paths: ["Containerfile"]
  workflow_dispatch:
env:
  IMAGE_NAME: robomaster-firmware

jobs:
  push-container:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile
            
      - name: Push
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
